version: '3.8'

services:
  web:
    build: .
    environment:
      - FLASK_APP=app
      - MONGO_USERNAME=${MONGO_APP_USERNAME}
      - MONGO_PASSWORD=${MONGO_APP_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./application/app/static:/app/static

  nginx:
    image: nginx:1.25.3
    ports:
      - "80:80"
    # Copy config files instead of mounting them
    volumes:
      - ./application/app/static:/app/static:ro
    # Add config files during build
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: default_conf
        target: /etc/nginx/conf.d/default.conf

  mongodb:
    image: mongo:5.0.22
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data:

configs:
  nginx_conf:
    file: ./nginx/nginx.conf
  default_conf:
    file: ./nginx/conf.d/default.conf