version: '3.8'

services:
  web:
    build:
      target: runtime
    ports:
      - "5000:5000"
    volumes:
      - ./application/app:/app/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: ["flask", "run", "--host=0.0.0.0"]

  nginx:
    ports:
      - "80:80"

  mongodb:
    ports:
      - "27017:27017"