services:
  web:
    extends:
      file: docker-compose.yaml
      service: web
    build:
      target: runtime
    environment:
      - FLASK_ENV=testing
      - TESTING=True
    command: ["python", "-m", "pytest", "tests/"]

  mongodb:
    extends:
      file: docker-compose.yaml
      service: mongodb

  nginx:
    extends:
      file: docker-compose.yaml
      service: nginx
    profiles:
      - "do-not-start"

volumes:
  mongodb_data: