services:
  web:
    extends:
      file: docker-compose.yaml
      service: web
    build:
      target: runtime
    environment:
      - FLASK_ENV=testing
      - TESTING=True
    ports:
      - "5000:5000"

  mongodb:
    extends:
      file: docker-compose.yaml
      service: mongodb
    ports:
      - "27017:27017"
    
  nginx:
    extends:
      file: docker-compose.yaml
      service: nginx

volumes:
  mongodb_data: